# This compose file will set up a single node kafka cluster on local along with Kafdrop UI
  version: '2'
  services:
    zookeeper:
      image: confluentinc/cp-zookeeper:7.4.4
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - '22181:2181'

    kafka:
      image: confluentinc/cp-kafka:7.4.4
      depends_on:
        - zookeeper
      ports:
        - '29092:29092'
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    kafdrop:
      image: obsidiandynamics/kafdrop
      depends_on:
        - kafka
      ports:
        - '9000:9000'
      environment:
        KAFKA_BROKERCONNECT: kafka:9092
        JVM_OPTS: -Xms32M -Xmx64M
        SERVER_SERVLET_CONTEXTPATH: /

    schema-registry:
      image: confluentinc/cp-schema-registry:latest
      hostname: schema-registry
      depends_on:
        - kafka
      ports:
        - "8081:8081"
      environment:
        SCHEMA_REGISTRY_HOST_NAME: schema-registry
        SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
        SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
        SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://localhost:29092
        SCHEMA_REGISTRY_DEBUG: 'true'